### ISSUE TITLE
Conda

### ISSUE THREAD

**Issue by rapgenic** [jupyter-xeus/xeus-octave#11]

**Comment by marimeireles** [comment]
hey @rapgenic, I'd like to help with  this one :)

I already created a recipe and built it locally, so I have a working package for conda.
The only problem is that I'm currently drawing it from my fork. To be able to have a conda recipe is necessary to have releases from github (for example), so do you mind of releasing a new version of `xeus-octave` for that? A 0.0.1 tag or so.
If you prefer I could also do it! But I need some admin permissions to your repo to do it.

With that it'll be possible to fix https://github.com/rapgenic/xeus-octave/issues/16, I already wrote the file for it too!

Anyways if you need assistance, please let me know. 🌸

**Comment by rapgenic** [comment]
Hi @marimeireles, thanks again for your interest and for helping :) Conda is completely new for me (and I don't use it), so this is great news!

Sure no problem creating a tag, however I'd rather call it 0.0.1beta or something like that, given the still experimental nature of this project... Would that still work?

I don't exactly know the nature of conda packages (I'll be studying a bit the next days), but I expect they will be described by a few files (something like package.json maybe?), but if that's the case it would be great if you could open a PR so that we can add them here as well (same goes for binder files, thank you for that as well :)

**Comment by rapgenic** [comment]
I have created the `0.0.1-beta` tag, I will rename it if necessary.

In the meantime a few questions have popped into my mind: 
* is there a public registry for conda recipes? 
* and would you like to have it published there or is it self contained? 
* If we want to publish it is there some information that will be shown on the info page (such as the readme, which needs an update #15...)

Please do not feel the need to answer right now, the next days I'll gather some informations on my own, as soon as I have a little more free time, I'm just asking in case you already are familiar with the ecosystem and know the answers

**Comment by marimeireles** [comment]
Hey @rapgenic, thanks for the swift reply!
So, to be able to have a package we have to publish it on [conda-forge](https://conda-forge.org/) and to do it it's not very complicated.
They have a pattern which is called "recipe", it's an `yaml` file with the instructions on how to build the package. It's actually pretty chill to do it with `xeus` things because the whole `xeus` ecosystem is there already, so, all you need to do is to follow their [sample recipe](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml) and make the pertinent changes.
I already created and tested one locally, as I said the only thing missing is linking it to your directory. I'll add you as a maintainer of the package (if you want) and then you'll have all the privileges on the recipe. Most of the maintenance work involved in having package is merging new versions in the `conda-forge` recipe. `conda-forge` has a bot that automatically perceives when I new version of the package is release in the original repository and creates an automatic update for the upstream. Most of the times this automatic generated new version of the package works perfectly and all we have to do is merge it, sometimes it might not, so we have to fix it manually.

>is there a public registry for conda recipes?

Yes, in their github for example: https://github.com/conda-forge?type=source, but also available in their website.

>and would you like to have it published there or is it self contained?

It has to be published there because as I explained earlier I'm just creating a recipe, they're actually doing all the magic of transforming in a package and serving it for us :)

>If we want to publish it is there some information that will be shown on the info page (such as the readme, which needs an update #15...)

The repo for the package only contains generic information about the package. In the recipe itself there is some space to add this kind of information:

```
about:
  home: https://github.com/rapgenic/xeus-octave
  license: GPL
  license_family: GPL-3
  license_file: LICENSE.txt
  summary: 'xeus kernel for octave'

  description: |
    xeus kernel for the mathematics-oriented syntax with built-in
    2D/3D plotting and visualization tools octave.
```

This is what I added, but you can either post your comments here and I make the changes now or you can make your changes once I open a PR in `conda-forge` or you make your changes after the package is merged and created. Either way works for me.

Just one more thing, regarding the versioning, there's no problem in adding words like `alpha` or `beta` but if you do then `conda-forge` won't be able to fetch them. So, for this one is it okay to flag it as `0.0.1`?

Also, hit me up if you have any questions about the use of `conda-forge`, I'm by no means an expert but been using it for a while. I'm around in gitter and by email!

**Comment by rapgenic** [comment]
Thank you for the detailed explanation!

I fixed the tag name, I would have preferred it to have the `beta` in it, but it's not a big deal anyways.

> I'll add you as a maintainer of the package (if you want)

Please do! It seems to have a quite low maintenance burden, however I was wondering if it is possible to have an automated way to check if everything works when updating the package: as I don't really use conda right now, it might be not that easy to check for me, unless you (I'm assuming that you use it regularly) are willing to do the most of the maintenance job, to which of course I can collaborate.

> This is what I added

As of now, just a little detail: maybe we should call it "Jupyter Xeus kernel" instead of only "Xeus kernel" given that probably not everybody knows Xeus but they surely know Jupyter. For everything else we'll see when everything is up and running...

> Also, hit me up if you have any questions about the use of conda-forge, I'm by no means an expert but been using it for a while. I'm around in gitter and by email!

Thank you for that, I'll keep that in mind!

**Comment by marimeireles** [comment]
>I fixed the tag name, I would have preferred it to have the beta in it, but it's not a big deal anyways.

It's no problem to tag the next (that you don't want a conda package for) that way =)

>As of now, just a little detail: maybe we should call it "Jupyter Xeus kernel" instead of only "Xeus kernel" given that probably not everybody knows Xeus but they surely know Jupyter. For everything else we'll see when everything is up and running...

I'd say following the pattern of the other `xeus` stuff we can leave it as it is! 

And no probs! I'll be maintaining it too. Thanks for being so nice!

**Comment by rapgenic** [comment]
That's great, many thanks! 

Let's use this issue for future updates

**Comment by rapgenic** [comment]
@marimeireles, please let's continue here the discussion we started about conda in #33, as it's not related to that issue.

We need to make a few things clearer, regarding opengl and the various platforms, as we've started many new things which kind of mixed up. 

I'm far from an expert on these matters, but here's how I view this complicated opengl and packaging thing:

First, OpenGL integration is handled through GLFW. GLFW provides various backends that support different platforms/OSs. Furthermore, on Linux, there are usually two variants of GLFW, one for X11 and one for Wayland (the two main window managers). 

GLFW does not automatically link against opengl, so we should take care of it by choosing the appropriate implementation.

Second, there should not be particular problems when building and using xoctave on desktops and laptops, as they usually have their own graphics driver installed, that provide the correct native GPU based opengl platform for rendering. Servers, or in general headless computers (e.g. Binder), on the other hand often don't have a graphics card, so we can't link against OpenGL native, but we need to rely on a CPU based implementation: enter osmesa. 

GLFW does support osmesa, but a package might not be available, or osmesa might be supported alongside the main backend but many dependencies could be introduced. That's why I added the possibility to fetch it and buid it in tree. 

So this is in my opinion the matrix of platforms vs libraries that we should support and for which we should have different packages:

| Platform | GLFW (note that we just need to link against `glfw3` for every case, as the correct variant will already be installed depending on the system) | OpenGL | Conda Package (we probably need one for each platform) | Use case |
| - | - | - | - | - |
| Linux X11 (GPU) | glfw-x11 | native opengl | xeus-octave-linux | Laptop/Desktop |
| Linux Wayland (GPU) | glfw-wayland | native opengl | xeus-octave-linux-wayland | Laptop/Desktop |
| Linuz Headless (CPU) | glfw-headless (if exists) or glfw in-tree | osmesa | xeus-octave-linux-headless | Binder/Old laptops |
| Mac OS (GPU) | glfw-cocoa | native opengl | xeus-octave-mac |  Laptop/Desktop |
| Mac OS (CPU) | **N/A** (and actually not needed, as I don't think there's a Mac without GPU) | **N/A** | |
| Windows | **TBD** | **TBD** | |

Last, OpenGL libraries: in Linux they are usually provided by the graphics drivers, or accessed via libglvnd (a sort of hardware independent proxy). I don't know about MacOS but I believe the cmake command `find_package(OpenGL)` should take care of everything. Osmesa then is a special linux only exception which is needed for headless computers (which is in our case mainly Binder). 

Whatever library we choose, I doubt it can be found in conda, because it depends on hardware (maybe only osmesa could be there, being a software only implementation).

I hope I haven't made any mistake and that this clears up the big picture a bit!

**Comment by marimeireles** [comment]
Hey @rapgenic.
Thanks, this makes everything much clearer :)!

I just talked to a conda-forge maintainer about this whole opengl mess thing. Conda actually doesn't take care of the different distributions of opengl, so it's up to the user to deal with this. So, through conda is not possible to make different releases depending on xorg/wayland. Sorry to not clarify it earlier, I didn't know.

I was able to make it work on Linux, thanks to your latest changes. I'll add my OSX changes now and give it a try. :)

About the binder stuff, I don't really understand details about binder's internals but I know it's served with a kubernets instance and I think it's an ubuntu linux with xorg... So I think it might work with the linux conda package I just built! I'm looking into it to learn more about it.
Also, it doesn't make sense to run a headless instance of octave is binder, I mean, it does because you can still have number outputs and so on, but we'd lose a lot if we don't have the graphs, right? (I don't really know what are the uses of octave).

But maybe it does make sense for some users to have a headless instance and then we can make an output recipe for this. What do you think?

Thanks again for the nice explanation! Helped a lot!

**Comment by rapgenic** [comment]
> Also, it doesn't make sense to run a headless instance of octave is binder, I mean, it does because you can still have number outputs and so on, but we'd lose a lot if we don't have the graphs, right? (I don't really know what are the uses of octave).

Well by headless I mean without a GPU/monitor, so the graphing capabilities should be supplied by osmesa. However if what you say is true, osmesa support might not be that important.

The main difference with of a headless build vs a "normal" would be that GLFW needs to be built with the osmesa backend instead of the X11 or Wayland backend, which is not most of the time.

> So, through conda is not possible to make different releases depending on xorg/wayland. 

I believe this is not related to opengl but only to GLFW, as (regardless of the opengl library, which we understood is up to the user) I don't think it can be built to support both Xorg and Wayland at the same time. 

I suppose that the GLFW conda package is built for Xorg, and that would be fine, as Wayland supports Xorg applications as well. So for now a single package based on GLFW X11, (supposing binder has Xorg in it) should be enough to satisfy almost all the possibilities (at least on Linux).

**Comment by marimeireles** [comment]
>Well by headless I mean without a GPU/monitor, so the graphing capabilities should be supplied by osmesa. 

Hum, I see.

The problem is that for binder to have graphics it needs all of these packages installed (like osmesa stuff for example).
Packages that are not coming with the default ubuntu system (right? I'm not sure, it didn't work out of the box on my linux machine). And I'm thinking in ways on how to get it installed on binder's servers.
[This](https://github.com/jupyterhub/repo2docker/blob/73ab48a42d8f818038540d0a15bc2b4f7d88d46e/repo2docker/buildpacks/base.py#L14) is the build template for binder. Just by quickly going over it I'd say it won't work out of the box. I'm looking into ways of installing OS packages on binder.

>I believe this is not related to opengl but only to GLFW, as (regardless of the opengl library, which we understood is up to the user) I don't think it can be built to support both Xorg and Wayland at the same time.

Yeah, I got that. I meant conda won't take care of any dependencies like osmesa stuff.

>So for now a single package based on GLFW X11, (supposing binder has Xorg in it) should be enough to satisfy almost all the possibilities (at least on Linux).

Yes! And it's currently working for macos too :)

**Comment by SylvainCorlay** [comment]
I am keen on closing this issue as we now have a proper conda package on conda-forge, and binder is working.

However, there is still some cargo culting going on around the way OpenGL is handled and it would be interesting to keep in mind the great documentation that @rapgenic posted here.
