### ISSUE TITLE
The build of octave packaged on conda-forge does not include fltk

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-xeus/xeus-octave#44]
So we need to disable `octave::feval("graphics_toolkit", ovl("fltk"));`.

Could we make this an opt-in, or detect if it is installed?

**Comment by SylvainCorlay** [comment]
Note: the build is done with the option `--without-fltk`.

**Comment by AntoinePrv** [comment]
Hi @rapgenic, I'll be working with @SylvainCorlay on this.

It seems like this call set the default graphic toolkit.

https://github.com/rapgenic/xeus-octave/blob/b5cc9bde26a861f1434f490fb46b8b65b2b91df9/src/xoctave_interpreter.cpp#L227

But then wouldn't it be overridden by one of the two statements afterwards? More surprisingly, when I commented out that line, the default graphical toolkit became `gnuplot`.

If we need to keep the `fltk` call, we could dynamically check [`available_graphics_toolkits`](https://docs.octave.org/interpreter/Graphics-Toolkits.html) and verify that `fltk` is in there.

I'm happy to send a PR for any option, but unsure which one is best.

**Comment by rapgenic** [comment]
Hi @AntoinePrv, you have discovered one of the magic pieces of code of this project!

At first sight that line is useless, however, for reasons unknown to me, without selecting a "wrong" graphic toolkit first, the following call does not have an effect, as you have noticed...

I do remember exploring in depth the octave code trying to understand what is happening but eventually giving up either because I didn't find the reason or because it wasn't easily fixable. 

If you don't have the fltk toolkit I suggest you try some other which is available, first, because I don't think that the gnuplot toolkit will work in a notebook (besides being inferior and about to be deprecated, I believe)

If you find a solution I'd be happy to merge it until @SylvainCorlay and I have done the transfer to the xeus organisation. After we have taken care of that I think you'll have write access to the repo, and there's no need to wait for my manual intervention to merge your work. Of course I'm always available if you need to do some code review or need some advice so feel free to ping me!
